{% set name = "qpax" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kevin-tracy/qpax/archive/v{{ version }}.tar.gz
  sha256: e1ce9192dce4a571ce2236687779040f9b7c122f6a64480ce9781924af8652a8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >=3.7
    - jax >=0.4.0
    - jaxlib >=0.4.0

test:
  imports:
    - qpax
  commands:
    - pip check
    - pytest
  requires:
    - pip
    - pytest
  source_files:
    - test/*

about:
  home: https://github.com/kevin-tracy/qpax
  summary: Differentiable QP solver in JAX.
  dev_url: https://github.com/kevin-tracy/qpax
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - flferretti
