{% set name = "qpax" %}
{% set version = "0.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kevin-tracy/qpax/archive/v{{ version }}.tar.gz
  sha256: 8725bc8184217b6e2f3c0541182d3d30fc0f05d96e237a920866dee4c37038b8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - jax >=0.4.0
    - jaxlib >=0.4.0

test:
  imports:
    - qpax
  commands:
    - pip check
    - pytest
  requires:
    - pip
    - pytest
    - python {{ python_min }}
  source_files:
    - test/*

about:
  home: https://github.com/kevin-tracy/qpax
  summary: Differentiable QP solver in JAX.
  dev_url: https://github.com/kevin-tracy/qpax
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - flferretti
