{% set name = "qpax" %}
{% set version = "0.0.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kevin-tracy/qpax/archive/v{{ version }}.tar.gz
  sha256: 30a7cc3d4809bfee5a66351aa7b512e3cdc00db612619625e3d84efe4a3b2d36

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - jax >=0.4.0
    - jaxlib >=0.4.0

test:
  imports:
    - qpax
  commands:
    - pip check
    - pytest
  requires:
    - pip
    - pytest
    - python {{ python_min }}
  source_files:
    - test/*

about:
  home: https://github.com/kevin-tracy/qpax
  summary: Differentiable QP solver in JAX.
  dev_url: https://github.com/kevin-tracy/qpax
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - flferretti
